version: "3.8"

services:
  hospital-db:
    image: postgres:15
    container_name: hospital_db
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
    ports:
      - "5433:5432"
    volumes:
      - ./hospital_db.sql:/docker-entrypoint-initdb.d/hospital_db.sql
