version: "3.8"

services:
  central-db:
    image: postgres:15
    container_name: central_fhir_db
    environment:
      POSTGRES_DB: carelock
      POSTGRES_USER: carelock_user
      POSTGRES_PASSWORD: carelock_pass
    ports:
      - "5434:5432"
    volumes:
      - ./database/central_fhir.sql:/docker-entrypoint-initdb.d/central_fhir.sql
